const SUBJECTIVE = {
   "sections":[
      {
         "fields":[
            {
               "name":"chief_complaint",
               "label":"Chief Complaint",
               "type":"input"
            },
            {
               "name":"hpi",
               "label":"History of Present Illness",
               "type":"input"
            },
            {
               "type":"subheading",
               "label":"Case Type & Device Usage"
            },
            {
               "name":"case_type",
               "label":"Case Type",
               "type":"radio",
               "options":[
                  {
                     "label":"Amputee",
                     "value":"amputee"
                  },
                  {
                     "label":"Non-amputee",
                     "value":"non_amputee"
                  }
               ]
            },
            {
               "name":"using_prosthesis",
               "label":"Using Prosthesis",
               "type":"radio",
               "options":[
                  {
                     "label":"Yes",
                     "value":"yes"
                  },
                  {
                     "label":"No",
                     "value":"no"
                  }
               ]
            },
            {
               "name":"using_orthosis",
               "label":"Using Orthosis",
               "type":"radio",
               "options":[
                  {
                     "label":"Yes",
                     "value":"yes"
                  },
                  {
                     "label":"No",
                     "value":"no"
                  }
               ]
            },
            {
               "type":"subheading",
               "label":"Stump Condition",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               }
            },
            {
               "name":"stump_side",
               "label":"Side",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"Right",
                     "value":"right"
                  },
                  {
                     "label":"Left",
                     "value":"left"
                  },
                  {
                     "label":"Bilateral",
                     "value":"bilateral"
                  }
               ]
            },
            {
               "name":"stump_condition",
               "label":"Stump Condition",
               "type":"checkbox-group",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"Healed",
                     "value":"healed"
                  },
                  {
                     "label":"Wound",
                     "value":"wound"
                  },
                  {
                     "label":"Swelling",
                     "value":"swelling"
                  },
                  {
                     "label":"Redness",
                     "value":"redness"
                  },
                  {
                     "label":"Sensitive",
                     "value":"sensitive"
                  },
                  {
                     "label":"Flabby",
                     "value":"flabby"
                  }
               ]
            },
            {
               "name":"stump_pain",
               "label":"Stump Pain",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"phantom_pain",
               "label":"Phantom Pain",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"phantom_sensation",
               "label":"Phantom Sensation",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"volume_fluctuation",
               "label":"Volume Fluctuation",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"sweating",
               "label":"Sweating",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"stump_other_issue",
               "label":"Other Issue",
               "type":"textarea",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               }
            },
            {
               "type":"subheading",
               "label":"Prosthetic Usage",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               }
            },
            {
               "name":"existing_user",
               "label":"Existing User",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"current_issue",
               "label":"Current Issue",
               "type":"checkbox-group",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Loose",
                     "value":"loose"
                  },
                  {
                     "label":"Pain",
                     "value":"pain"
                  },
                  {
                     "label":"Heavy",
                     "value":"heavy"
                  },
                  {
                     "label":"Unstable",
                     "value":"unstable"
                  },
                  {
                     "label":"Cosmetic",
                     "value":"cosmetic"
                  },
                  {
                     "label":"Broken",
                     "value":"broken"
                  },
                  {
                     "label":"Nil",
                     "value":"nil"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"wearing_time",
               "label":"Wearing Time",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Not using",
                     "value":"not_using"
                  },
                  {
                     "label":"<2h",
                     "value":"less_2h"
                  },
                  {
                     "label":"2–6h",
                     "value":"between_2_6h"
                  },
                  {
                     "label":">6h",
                     "value":"more_6h"
                  }
               ]
            },
            {
               "name":"donning_ability",
               "label":"Donning Ability",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Independent",
                     "value":"independent"
                  },
                  {
                     "label":"Assist",
                     "value":"assist"
                  },
                  {
                     "label":"Unable",
                     "value":"unable"
                  }
               ]
            },
            {
               "name":"suspension_issue",
               "label":"Suspension Issue",
               "type":"checkbox-group",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Slipping",
                     "value":"slipping"
                  },
                  {
                     "label":"Difficult donning",
                     "value":"difficult_donning"
                  },
                  {
                     "label":"Pain",
                     "value":"pain"
                  },
                  {
                     "label":"Nil",
                     "value":"nil"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"prosthetic_other_issue",
               "label":"Other Issue",
               "type":"textarea",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               }
            },
            {
               "type":"subheading",
               "label":"Functional Level",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               }
            },
            {
               "name":"mobility_level",
               "label":"Mobility Level",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Wheelchair",
                     "value":"wheelchair"
                  },
                  {
                     "label":"Household Ambulator",
                     "value":"household_ambulator"
                  },
                  {
                     "label":"Community Ambulator",
                     "value":"community_ambulator"
                  }
               ]
            },
            {
               "name":"functional_level_assistive_device",
               "label":"Assistive Device",
               "type":"checkbox-group",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"None",
                     "value":"none"
                  },
                  {
                     "label":"Cane",
                     "value":"cane"
                  },
                  {
                     "label":"Walker",
                     "value":"walker"
                  },
                  {
                     "label":"Crutches",
                     "value":"crutches"
                  }
               ]
            },
            {
               "name":"functional_balance_issue",
               "label":"Balance Issue",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
                "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"functional_other_issue",
               "label":"Other Issue",
               "type":"textarea",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               }
            },
            {
               "type":"subheading",
               "label":"Functional Status"
            },
            {
               "name":"functional_difficulty",
               "label":"Functional Difficulty",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Walking",
                     "value":"walking"
                  },
                  {
                     "label":"Standing",
                     "value":"standing"
                  },
                  {
                     "label":"Transfer",
                     "value":"transfer"
                  },
                  {
                     "label":"Stairs",
                     "value":"stairs"
                  },
                  {
                     "label":"ADL",
                     "value":"adl"
                  },
                  {
                     "label":"RTW",
                     "value":"rtw"
                  },
                  {
                     "label":"Balance",
                     "value":"balance"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"pain",
               "label":"Pain",
               "type":"radio",
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"pain_location",
               "label":"Pain Location",
               "type":"checkbox-group",
               "showIf":{
                  "field":"pain",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Limb",
                     "value":"limb"
                  },
                  {
                     "label":"Joint",
                     "value":"joint"
                  },
                  {
                     "label":"Back",
                     "value":"back"
                  },
                  {
                     "label":"Stump",
                     "value":"stump"
                  },
                  {
                     "label":"General",
                     "value":"general"
                  }
               ]
            },
            {
               "name":"pain_score",
               "label":"Pain Score(Visual Analog Scale)",
               "type":"scale-slider",
               "min":0,
               "max":10,
               "ranges":[
                  {
                     "min":0,
                     "max":1,
                     "label":"Mild",
                     "color":"#22c55e"
                  },
                  {
                     "min":1,
                     "max":5,
                     "label":"Moderate",
                     "color":"#facc15"
                  },
                  {
                     "min":5,
                     "max":10,
                     "label":"Severe",
                     "color":"#ef4444"
                  }
               ],
               "showValue":true,
               "showIf":{
                  "field":"pain",
                  "equals":"yes"
               }
            },
            {
               "name":"pain_timing",
               "label":"Pain Timing",
               "type":"checkbox-group",
               "showIf":{
                  "field":"pain",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Rest",
                     "value":"rest"
                  },
                  {
                     "label":"Movement",
                     "value":"movement"
                  },
                  {
                     "label":"Night",
                     "value":"night"
                  },
                  {
                     "label":"Weight-bearing",
                     "value":"weight_bearing"
                  }
               ]
            },
            {
               "name":"functional_status_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Mobility"
            },
            {
               "name":"mobility_status",
               "label":"Mobility Status",
               "type":"radio",
               "options":[
                  {
                     "label":"Independent",
                     "value":"independent"
                  },
                  {
                     "label":"Supervision",
                     "value":"supervision"
                  },
                  {
                     "label":"Min Assist",
                     "value":"min_assist"
                  },
                  {
                     "label":"Mod Assist",
                     "value":"mod_assist"
                  },
                  {
                     "label":"Max Assist",
                     "value":"max_assist"
                  },
                  {
                     "label":"Dependent",
                     "value":"dependent"
                  }
               ]
            },
            {
               "name":"assistive_device",
               "label":"Assistive Device",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Cane",
                     "value":"cane"
                  },
                  {
                     "label":"Quadripod",
                     "value":"quadripod"
                  },
                  {
                     "label":"Walker",
                     "value":"walker"
                  },
                  {
                     "label":"Crutches",
                     "value":"crutches"
                  },
                  {
                     "label":"Wheelchair",
                     "value":"wheelchair"
                  },
                  {
                     "label":"None",
                     "value":"none"
                  }
               ]
            },
            {
               "name":"walking_distance",
               "label":"Walking Distance",
               "type":"radio",
               "options":[
                  {
                     "label":"Unable",
                     "value":"unable"
                  },
                  {
                     "label":"<10m",
                     "value":"less_10m"
                  },
                  {
                     "label":"Household",
                     "value":"household"
                  },
                  {
                     "label":"Community",
                     "value":"community"
                  }
               ]
            },
            {
               "name":"balance_issue",
               "label":"Balance Issue",
               "type":"radio",
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"fall_history",
               "label":"Fall History",
               "type":"radio",
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"fall_frequency",
               "label":"Fall Frequency",
               "type":"radio",
               "showIf":{
                  "field":"fall_history",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Once",
                     "value":"once"
                  },
                  {
                     "label":"Occasional",
                     "value":"occasional"
                  },
                  {
                     "label":"Recurrent",
                     "value":"recurrent"
                  }
               ]
            },
            {
               "name":"mobility_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Limb Condition"
            },
            {
               "name":"skin_condition",
               "label":"Skin Condition",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Normal",
                     "value":"normal"
                  },
                  {
                     "label":"Redness",
                     "value":"redness"
                  },
                  {
                     "label":"Wound",
                     "value":"wound"
                  },
                  {
                     "label":"Scar",
                     "value":"scar"
                  },
                  {
                     "label":"Sensitive",
                     "value":"sensitive"
                  }
               ]
            },
            {
               "name":"sensation_issue",
               "label":"Sensation Issue",
               "type":"radio",
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"sound_limb_condition",
               "label":"Sound Limb Condition",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Normal",
                     "value":"normal"
                  },
                  {
                     "label":"Pain",
                     "value":"pain"
                  },
                  {
                     "label":"Weakness",
                     "value":"weakness"
                  },
                  {
                     "label":"Wound",
                     "value":"wound"
                  },
                  {
                     "label":"Deformity",
                     "value":"deformity"
                  }
               ]
            },
            {
               "name":"limb_condition_remarks",
               "label":"Remarks",
               "type":"textarea"
            }
         ]
      }
   ]
}

const OBJECTIVE = {
   "sections":[
      {
         "fields":[
            {
               "type":"subheading",
               "label":"Case Type & Device Usage"
            },
            {
               "name":"case_type",
               "label":"Case Type",
               "type":"radio",
               "options":[
                  {
                     "label":"Amputee",
                     "value":"amputee"
                  },
                  {
                     "label":"Non-amputee",
                     "value":"non_amputee"
                  }
               ]
            },
            {
               "name":"using_prosthesis",
               "label":"Using Prosthesis",
               "type":"radio",
               "options":[
                  {
                     "label":"Yes",
                     "value":"yes"
                  },
                  {
                     "label":"No",
                     "value":"no"
                  }
               ]
            },
            {
               "name":"using_orthosis",
               "label":"Using Orthosis",
               "type":"radio",
               "options":[
                  {
                     "label":"Yes",
                     "value":"yes"
                  },
                  {
                     "label":"No",
                     "value":"no"
                  }
               ]
            },
            {
               "type":"subheading",
               "label":"Muscle Strength"
            },
            {
               "name":"strength_change",
               "label":"Strength Change",
               "type":"radio",
               "options":[
                  {
                     "label":"Improved",
                     "value":"improved"
                  },
                  {
                     "label":"Same",
                     "value":"same"
                  },
                  {
                     "label":"Reduced",
                     "value":"reduced"
                  }
               ]
            },
            {
               "name":"affected_area_weakness",
               "label":"Affected Area (Weakness)",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Shoulder",
                     "value":"shoulder"
                  },
                  {
                     "label":"Elbow",
                     "value":"elbow"
                  },
                  {
                     "label":"Wrist",
                     "value":"wrist"
                  },
                  {
                     "label":"Hip",
                     "value":"hip"
                  },
                  {
                     "label":"Knee",
                     "value":"knee"
                  },
                  {
                     "label":"Ankle",
                     "value":"ankle"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"selected_mmt",
               "label":"Selected MMT",
               "type":"textarea"
            },
            {
               "name":"grip_strength_change",
               "label":"Grip Strength Change",
               "type":"radio",
               "options":[
                  {
                     "label":"Improved",
                     "value":"improved"
                  },
                  {
                     "label":"Same",
                     "value":"same"
                  },
                  {
                     "label":"Reduced",
                     "value":"reduced"
                  }
               ]
            },
            {
               "name":"muscle_strength_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Tone & Tightness"
            },
            {
               "type":"row",
               "compact":true,
               "fields":[
                  {
                     "name":"pe_muscle_tone_side",
                     "label":"Muscle Tone",
                     "type":"checkbox-group",
                     "position":"side",
                     "options":[
                        {
                           "label":"Right",
                           "value":"right"
                        },
                        {
                           "label":"Left",
                           "value":"left"
                        }
                     ]
                  }
               ]
            },
            {
               "type":"row",
               "compact":true,
               "fields":[
                  {
                     "name":"pe_muscle_tone_right",
                     "label":"Right",
                     "type":"radio",
                     "showIf":{
                        "field":"pe_muscle_tone_side",
                        "includes":"right"
                     },
                     "options":[
                        {
                           "label":"Normal",
                           "value":"normal"
                        },
                        {
                           "label":"Hypotonia",
                           "value":"hypotonia"
                        },
                        {
                           "label":"Hypertonia",
                           "value":"hypertonia"
                        }
                     ]
                  },
                  {
                     "name":"pe_muscle_tone_left",
                     "label":"Left",
                     "type":"radio",
                     "showIf":{
                        "field":"pe_muscle_tone_side",
                        "includes":"left"
                     },
                     "options":[
                        {
                           "label":"Normal",
                           "value":"normal"
                        },
                        {
                           "label":"Hypotonia",
                           "value":"hypotonia"
                        },
                        {
                           "label":"Hypertonia",
                           "value":"hypertonia"
                        }
                     ]
                  }
               ]
            },
            {
               "type":"row",
               "compact":true,
               "fields":[
                  {
                     "name":"pe_muscle_tone_comment_right",
                     "label":"Muscle Tone Comment – Right",
                     "type":"input",
                     "showIf":{
                        "field":"pe_muscle_tone_right",
                        "oneOf":[
                           "hypotonia",
                           "hypertonia"
                        ],
                        "and":{
                           "field":"pe_muscle_tone_side",
                           "includes":"right"
                        }
                     }
                  },
                  {
                     "name":"pe_muscle_tone_comment_left",
                     "label":"Muscle Tone Comment – Left",
                     "type":"input",
                     "showIf":{
                        "field":"pe_muscle_tone_left",
                        "oneOf":[
                           "hypotonia",
                           "hypertonia"
                        ],
                        "and":{
                           "field":"pe_muscle_tone_side",
                           "includes":"left"
                        }
                     }
                  }
               ]
            },
            {
               "name":"pe_mas_launcher",
               "label":"",
               "type":"assessment-launcher",
               "options":[
                  {
                     "label":"Modified Ashworth Scale (MAS)",
                     "value":"mas_scale"
                  }
               ]
            },
            {
               "name":"tightness",
               "label":"Tightness",
               "type":"radio",
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"tone_tightness_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Range of Motion"
            },
            {
               "name":"rom_launcher",
               "label":"",
               "type":"assessment-launcher",
               "options":[
                  {
                     "label":"Range Of Motion (ROM)",
                     "value":"rom"
                  }
               ]
            },
            {
               "name":"contracture",
               "label":"Contracture",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Shoulder",
                     "value":"shoulder"
                  },
                  {
                     "label":"Elbow",
                     "value":"elbow"
                  },
                  {
                     "label":"Wrist",
                     "value":"wrist"
                  },
                  {
                     "label":"Hip",
                     "value":"hip"
                  },
                  {
                     "label":"Knee",
                     "value":"knee"
                  },
                  {
                     "label":"Ankle",
                     "value":"ankle"
                  }
               ]
            },
            {
               "name":"contracture_angle",
               "label":"Contracture Angle",
               "type":"input",
               "showIf":{
                  "field":"contracture",
                  "hasValue":true
               }
            },
            {
               "name":"rom_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Sensory"
            },
            {
               "name":"sensation_change",
               "label":"Sensation Change",
               "type":"radio",
               "options":[
                  {
                     "label":"Intact",
                     "value":"intact"
                  },
                  {
                     "label":"Reduced",
                     "value":"reduced"
                  },
                  {
                     "label":"Altered",
                     "value":"altered"
                  }
               ]
            },
            {
               "name":"proprioception",
               "label":"Proprioception",
               "type":"radio",
               "options":[
                  {
                     "label":"Intact",
                     "value":"intact"
                  },
                  {
                     "label":"Impaired",
                     "value":"impaired"
                  }
               ]
            },
            {
               "name":"sensory_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Gait Observation"
            },
            {
               "name":"mobility_status",
               "label":"Mobility Status",
               "type":"radio",
               "options":[
                  {
                     "label":"Independent",
                     "value":"independent"
                  },
                  {
                     "label":"With Aid",
                     "value":"with_aid"
                  },
                  {
                     "label":"Wheelchair",
                     "value":"wheelchair"
                  },
                  {
                     "label":"Unable",
                     "value":"unable"
                  }
               ]
            },
            {
               "name":"walking_distance",
               "label":"Walking Distance",
               "type":"radio",
               "options":[
                  {
                     "label":"Unable",
                     "value":"unable"
                  },
                  {
                     "label":"<10m",
                     "value":"less_10m"
                  },
                  {
                     "label":"Household",
                     "value":"household"
                  },
                  {
                     "label":"Community",
                     "value":"community"
                  }
               ]
            },
            {
               "name":"assistive_device",
               "label":"Assistive Device",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"None",
                     "value":"none"
                  },
                  {
                     "label":"Cane",
                     "value":"cane"
                  },
                  {
                     "label":"Quadripod",
                     "value":"quadripod"
                  },
                  {
                     "label":"Walker",
                     "value":"walker"
                  },
                  {
                     "label":"Crutches",
                     "value":"crutches"
                  },
                  {
                     "label":"Wheelchair",
                     "value":"wheelchair"
                  }
               ]
            },
            {
               "name":"weight_bearing",
               "label":"Weight Bearing",
               "type":"radio",
               "options":[
                  {
                     "label":"Full",
                     "value":"full"
                  },
                  {
                     "label":"Partial",
                     "value":"partial"
                  },
                  {
                     "label":"Non-weight Bearing",
                     "value":"non_weight_bearing"
                  }
               ]
            },
            {
               "name":"gait_pattern",
               "label":"Gait Pattern",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Normal",
                     "value":"normal"
                  },
                  {
                     "label":"Antalgic",
                     "value":"antalgic"
                  },
                  {
                     "label":"Hemiplegic",
                     "value":"hemiplegic"
                  },
                  {
                     "label":"Ataxic",
                     "value":"ataxic"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"gait_deviation",
               "label":"Gait Deviation",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Foot Drop",
                     "value":"foot_drop"
                  },
                  {
                     "label":"Circumduction",
                     "value":"circumduction"
                  },
                  {
                     "label":"Hip Hiking",
                     "value":"hip_hiking"
                  },
                  {
                     "label":"Knee Hyperextension",
                     "value":"knee_hyperextension"
                  },
                  {
                     "label":"Toe Drag",
                     "value":"toe_drag"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"step_length",
               "label":"Step Length",
               "type":"radio",
               "options":[
                  {
                     "label":"Symmetrical",
                     "value":"symmetrical"
                  },
                  {
                     "label":"Reduced",
                     "value":"reduced"
                  }
               ]
            },
            {
               "name":"trunk_control",
               "label":"Trunk Control",
               "type":"radio",
               "options":[
                  {
                     "label":"Good",
                     "value":"good"
                  },
                  {
                     "label":"Fair",
                     "value":"fair"
                  },
                  {
                     "label":"Poor",
                     "value":"poor"
                  }
               ]
            },
            {
               "name":"foot_clearance",
               "label":"Foot Clearance",
               "type":"radio",
               "options":[
                  {
                     "label":"Normal",
                     "value":"normal"
                  },
                  {
                     "label":"Reduced",
                     "value":"reduced"
                  },
                  {
                     "label":"Absent",
                     "value":"absent"
                  }
               ]
            },
            {
               "name":"ankle_control",
               "label":"Ankle Control",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Normal",
                     "value":"normal"
                  },
                  {
                     "label":"Supination",
                     "value":"supination"
                  },
                  {
                     "label":"Pronation",
                     "value":"pronation"
                  },
                  {
                     "label":"Foot Drop",
                     "value":"foot_drop"
                  }
               ]
            },
            {
               "name":"knee_control",
               "label":"Knee Control",
               "type":"radio",
               "options":[
                  {
                     "label":"Stable",
                     "value":"stable"
                  },
                  {
                     "label":"Buckling",
                     "value":"buckling"
                  },
                  {
                     "label":"Hyperextension",
                     "value":"hyperextension"
                  }
               ]
            },
            {
               "name":"hip_hiking",
               "label":"Hip Hiking",
               "type":"radio",
               "options":[
                  {
                     "label":"None",
                     "value":"none"
                  },
                  {
                     "label":"Mild",
                     "value":"mild"
                  },
                  {
                     "label":"Moderate",
                     "value":"moderate"
                  },
                  {
                     "label":"Severe",
                     "value":"severe"
                  }
               ]
            },
            {
               "name":"upper_limb_function",
               "label":"Upper Limb Function",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"Normal Arm Swing",
                     "value":"normal_arm_swing"
                  },
                  {
                     "label":"Reduced Arm Swing",
                     "value":"reduced_arm_swing"
                  },
                  {
                     "label":"Uses Walking Aid",
                     "value":"uses_walking_aid"
                  },
                  {
                     "label":"Weight Support on Aid",
                     "value":"weight_support_on_aid"
                  },
                  {
                     "label":"Guarding Position",
                     "value":"guarding_position"
                  }
               ]
            },
            {
               "name":"gait_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Joint Assessment"
            },
            {
               "name":"joint_change",
               "label":"Joint Change Since Last Review",
               "type":"radio",
               "options":[
                  {
                     "label":"No Change",
                     "value":"no_change"
                  },
                  {
                     "label":"Improved",
                     "value":"improved"
                  },
                  {
                     "label":"Worse",
                     "value":"worse"
                  }
               ]
            },
            {
               "name":"joint_stability",
               "label":"Joint Stability",
               "type":"radio",
               "options":[
                  {
                     "label":"Stable",
                     "value":"stable"
                  },
                  {
                     "label":"Mild Instability",
                     "value":"mild_instability"
                  },
                  {
                     "label":"Severe Instability",
                     "value":"severe_instability"
                  }
               ]
            },
            {
               "name":"deformity",
               "label":"Deformity",
               "type":"checkbox-group",
               "options":[
                  {
                     "label":"None",
                     "value":"none"
                  },
                  {
                     "label":"Varus",
                     "value":"varus"
                  },
                  {
                     "label":"Valgus",
                     "value":"valgus"
                  },
                  {
                     "label":"Equinus",
                     "value":"equinus"
                  },
                  {
                     "label":"Flexion",
                     "value":"flexion"
                  }
               ]
            },
            {
               "name":"joint_swelling",
               "label":"Joint Swelling",
               "type":"radio",
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"joint_tenderness",
               "label":"Joint Tenderness",
               "type":"radio",
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"joint_assessment_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Stump Assessment",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               }
            },
            {
               "name":"stump_skin",
               "label":"Stump Skin",
               "type":"checkbox-group",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"Normal",
                     "value":"normal"
                  },
                  {
                     "label":"Redness",
                     "value":"redness"
                  },
                  {
                     "label":"Wound",
                     "value":"wound"
                  },
                  {
                     "label":"Scar",
                     "value":"scar"
                  },
                  {
                     "label":"Adherent",
                     "value":"adherent"
                  }
               ]
            },
            {
               "name":"volume_fluctuation",
               "label":"Volume Fluctuation",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"stump_tenderness",
               "label":"Stump Tenderness",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
                "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"edema",
               "label":"Edema",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
                "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"active_wound",
               "label":"Active Wound",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Yes",
                     "value":"yes"
                  }
               ]
            },
            {
               "name":"residual_limb_control",
               "label":"Residual Limb Control",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"Good",
                     "value":"good"
                  },
                  {
                     "label":"Fair",
                     "value":"fair"
                  },
                  {
                     "label":"Poor",
                     "value":"poor"
                  }
               ]
            },
            {
               "name":"residual_limb_strength",
               "label":"Residual Limb Strength",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"Good",
                     "value":"good"
                  },
                  {
                     "label":"Fair",
                     "value":"fair"
                  },
                  {
                     "label":"Poor",
                     "value":"poor"
                  }
               ]
            },
            {
               "name":"stump_assessment_remarks",
               "label":"Remarks",
               "type":"textarea",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               }
            },
            {
               "type":"subheading",
               "label":"Alignment / Prosthetic Check",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               }
            },
            {
               "name":"prosthesis_fit",
               "label":"Prosthesis Fit",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Good",
                     "value":"good"
                  },
                  {
                     "label":"Loose",
                     "value":"loose"
                  },
                  {
                     "label":"Tight",
                     "value":"tight"
                  }
               ]
            },
            {
               "name":"suspension",
               "label":"Suspension",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Secure",
                     "value":"secure"
                  },
                  {
                     "label":"Loose",
                     "value":"loose"
                  }
               ]
            },
            {
               "name":"alignment",
               "label":"Alignment",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Good",
                     "value":"good"
                  },
                  {
                     "label":"Needs adjustment",
                     "value":"needs_adjustment"
                  }
               ]
            },
            {
               "name":"height_with_prosthesis",
               "label":"Height with Prosthesis",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Equal",
                     "value":"equal"
                  },
                  {
                     "label":"Short",
                     "value":"short"
                  },
                  {
                     "label":"Long",
                     "value":"long"
                  }
               ]
            },
            {
               "name":"gait_with_prosthesis",
               "label":"Gait with Prosthesis",
               "type":"radio",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Stable",
                     "value":"stable"
                  },
                  {
                     "label":"Unstable",
                     "value":"unstable"
                  }
               ]
            },
            {
               "name":"k_level",
               "label":"K-Level",
               "type":"single-select",
               "readOnly":false,
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"K0",
                     "value":"k0"
                  },
                  {
                     "label":"K1",
                     "value":"k1"
                  },
                  {
                     "label":"K2",
                     "value":"k2"
                  },
                  {
                     "label":"K3",
                     "value":"k3"
                  },
                  {
                     "label":"K4",
                     "value":"k4"
                  }
               ]
            },
            {
               "name":"current_prosthetic_issue",
               "label":"Current Prosthetic Issue",
               "type":"checkbox-group",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               },
               "options":[
                  {
                     "label":"Pain",
                     "value":"pain"
                  },
                  {
                     "label":"Poor fit",
                     "value":"poor_fit"
                  },
                  {
                     "label":"Loose",
                     "value":"loose"
                  },
                  {
                     "label":"Broken",
                     "value":"broken"
                  },
                  {
                     "label":"Heavy",
                     "value":"heavy"
                  },
                  {
                     "label":"Alignment",
                     "value":"alignment"
                  },
                  {
                     "label":"Cosmetic",
                     "value":"cosmetic"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"prosthetic_check_remarks",
               "label":"Remarks",
               "type":"textarea",
               "showIf":{
                  "field":"using_prosthesis",
                  "equals":"yes"
               }
            }
         ]
      }
   ]
}
const ASSESSMENT = {
   "sections":[
      {
         "fields":[
            {
               "type":"input",
               "name":"clinical_impression",
               "label":"Clinical Impression"
            },
            {
               "name":"problem_listing",
               "label":"Problem Listing",
               "type":"textarea",
               "readOnly":true
            },
            {
               "name":"rehab_potential",
               "label":"Rehab Potential",
               "type":"single-select",
               "options":[
                  {
                     "label":"UL",
                     "value":"ul"
                  },
                  {
                     "label":"LL",
                     "value":"ll"
                  },
                  {
                     "label":"Others",
                     "value":"others"
                  }
               ]
            },
            {
               "name":"assessment_remarks",
               "label":"Remarks",
               "type":"textarea"
            },
            {
               "type":"subheading",
               "label":"Amputee Assessment",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               }
            },
            {
               "name":"stump_concern",
               "label":"Stump Concern",
               "type":"textarea",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               }
            },
            {
               "name":"suitable_for_restoration",
               "label":"Suitable for Restoration",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"Yes",
                     "value":"yes"
                  },
                  {
                     "label":"No",
                     "value":"no"
                  },
                  {
                     "label":"Defer",
                     "value":"defer"
                  }
               ]
            },
            {
               "name":"donning_ability_assessment",
               "label":"Donning Ability",
               "type":"radio",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"Independent",
                     "value":"independent"
                  },
                  {
                     "label":"Assist",
                     "value":"assist"
                  },
                  {
                     "label":"Unable",
                     "value":"unable"
                  }
               ]
            },
            {
               "name":"existing_prosthesis_issue",
               "label":"Existing Prosthesis Issue",
               "type":"checkbox-group",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               },
               "options":[
                  {
                     "label":"None",
                     "value":"none"
                  },
                  {
                     "label":"Poor fit",
                     "value":"poor_fit"
                  },
                  {
                     "label":"Pain",
                     "value":"pain"
                  },
                  {
                     "label":"Alignment issue",
                     "value":"alignment_issue"
                  },
                  {
                     "label":"Broken",
                     "value":"broken"
                  }
               ]
            },
            {
               "name":"amputee_assessment_remarks",
               "label":"Remarks",
               "type":"textarea",
               "showIf":{
                  "field":"case_type",
                  "equals":"amputee"
               }
            }
         ]
      }
   ]
}

const PLAN = {
   "sections":[
      {
         "fields":[
            {
               "type":"subheading",
               "label":"Short Term Goals (2–4 Weeks)"
            },
            {
               "type":"dynamic-goals",
               "name":"short_term_goals"
            },
            {
               "type":"subheading",
               "label":"Long Term Goals (6–12 Weeks)"
            },
            {
               "type":"dynamic-goals",
               "name":"long_term_goals"
            },
            {
               "name":"goal",
               "label":"Goal",
               "type":"radio",
               "options":[
                  {
                     "label":"Short Term",
                     "value":"short_term"
                  },
                  {
                     "label":"Long Term",
                     "value":"long_term"
                  }
               ]
            },
            {
               "name":"intervention_required",
               "label":"Intervention Required",
               "type":"single-select",
               "options":[
                  {
                     "label":"Prescription",
                     "value":"prescription"
                  },
                  {
                     "label":"Repair",
                     "value":"repair"
                  },
                  {
                     "label":"No Intervention",
                     "value":"no_intervention"
                  }
               ]
            },
            {
               "name":"prescription_type",
               "label":"Prescription Type",
               "type":"single-select",
               "showIf":{
                  "field":"intervention_required",
                  "equals":"prescription"
               },
               "options":[
                  {
                     "label":"Prosthetic",
                     "value":"prosthetic"
                  },
                  {
                     "label":"Orthotic",
                     "value":"orthotic"
                  }
               ]
            },
            {
               "name":"training",
               "label":"Training",
               "type":"input",
               "placeholder":"Stump bandaging / Prosthetic donning & doffing / Gait training / Others"
            },
            {
               "name":"education",
               "label":"Education",
               "type":"input",
               "placeholder":"Stump bandaging / Prosthetic donning & doffing / Skin care / Others"
            },
            {
               "name":"plan_remarks",
               "label":"Remarks",
               "type":"textarea"
            }
         ]
      }
   ]
}

export default {
  PLAN,
  OBJECTIVE,
  SUBJECTIVE,
  ASSESSMENT,
};
