# Nodejs
FROM node:25.8.0

# Working directory
WORKDIR /React

# Copy dependencies files
COPY package.json package-lock.json ./

# Installing dependencies
RUN npm install

# Copy current directory
COPY . .

# Expose port
EXPOSE 3000

# Run application
CMD ["npm", "start"]