
import React, { useEffect, useState, createContext } from "react";
import CommonFormBuilder from "../../CommonComponenets/FormBuilder";
import { localDateTimeString } from "../../../shared/utils/dateFormatter";
import PatientCard from "../../../shared/cards/PatientCard";



/* ---------------- PATIENT CARD ---------------- */
function PatientInformationBlock({ patient, patientHistory, setPatientHistory }) {
  if (!patient) return null;

  const safe = (v) => v ?? "-";
  const formatDate = (d) => d ? new Date(d).toLocaleDateString() : "-";

  return (
    <div style={{ marginBottom: 24 }}>
      <div style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
        gap: 12,
        fontSize: 14
      }}>
        <div><b>Name:</b> {safe(patient.name)}</div>
        <div><b>IC:</b> {safe(patient.id)}</div>
        <div><b>DOB:</b> {formatDate(patient.dob)}</div>

        <div><b>Age / Gender:</b> {safe(patient.age)} / {safe(patient.sex)}</div>
        <div><b>ICD:</b> {safe(patient.icd)}</div>
        <div><b>Date of Assessment:</b> {new Date().toLocaleDateString()}</div>

        <div><b>Date of Onset:</b> {formatDate(patient.date_of_onset)}</div>
        <div><b>Duration of Diagnosis:</b> -</div>
        <div><b>Primary Diagnosis:</b> {safe(patient.diagnosis_history)}</div>

        <div><b>Secondary Diagnosis:</b> {safe(patient.medical_history)}</div>
        <div><b>Dominant Side:</b> {safe(patient.dominant_side)}</div>
        <div><b>Language Preference:</b> {safe(patient.language_preference)}</div>

        <div><b>Education Level:</b> {safe(patient.education_background)}</div>
        <div><b>Occupation:</b> {safe(patient.occupation)}</div>
        <div><b>Work Status:</b> {safe(patient.employment_status)}</div>

        <div><b>Driving Status:</b> {safe(patient.driving_status)}</div>
        <div><b>PP/OB:</b> {safe(patient.pp_ob)}</div>
        <div><b>Weight:</b> {patient.weight ? `${patient.weight} kg` : "-"}</div>

        {/* ===== HISTORY ===== */}
        <div style={{ gridColumn: "1 / -1", marginTop: 10 }}>
        
           <h3>Patient History</h3>
        
                  <div>
                    <b>Past Medical History</b>
                    <input
                      style={input}
                      value={patientHistory.past_medical_history}
                      onChange={(e) =>
                        setPatientHistory(prev => ({
                          ...prev,
                          past_medical_history: e.target.value
                        }))
                      }
                    />
                  </div>

          
          <div>
                    <b>Family History</b>
                    <input
                      style={input}
                      value={patientHistory.past_family_history}
                      onChange={(e) =>
                        setPatientHistory(prev => ({
                          ...prev,
                          past_family_history: e.target.value
                        }))
                      }
                    />
                  </div>

        
           <div>
                    <b>Allergies</b>
                    <input
                      style={input}
                      value={patientHistory.alerts_and_allergies}
                      onChange={(e) =>
                        setPatientHistory(prev => ({
                          ...prev,
                          alerts_and_allergies: e.target.value
                        }))
                      }
                    />
                  </div>

          <button style={alertBtn}>🚨 Alerts</button>
        </div>
      </div>
    </div>
  );
}

/* ---------------- MAIN COMPONENT ---------------- */

const YES_NO = [
  { label: "Yes", value: "yes" },
  { label: "No", value: "no" }
];


export default function PsychologyProgress({
  patient,
  onSubmit,
  onBack
}) {
  const [values, setValues] = useState({});
  
  const [submitted, setSubmitted] = useState(false);
  const [activeTab, setActiveTab] = useState("subjective");
  const PatientContext = createContext(null);
  const [patientHistory, setPatientHistory] = useState({
    past_medical_history: "",
    past_family_history: "",
    alerts_and_allergies: ""
  });
 
  
 
  const storageKey = patient
    ? `psychology_follow_up_assessment_draft_${patient.id}`
    : null;

  /* LOAD DRAFT */
  useEffect(() => {
    if (!storageKey) return;
    const saved = localStorage.getItem(storageKey);
    if (saved) {
      const parsed = JSON.parse(saved);
      setValues(parsed.values || {});
    }
  }, [storageKey]);

  /* AUTO POPULATE */
 useEffect(() => {
    if (!patient) return;

    setValues(v => ({
      ...v,
      psychiatric_history_autogenerated:
        patient.psychiatric_history || patient.medical_history || "No data available",
      family_medical_history_autogenerated:
        patient.family_history || patient.diagnosis_history || "No data available",
      drug_history_autogenerated:
        patient.medications || patient.drug_history || "No data available"
    }));
  }, [patient]);

  // const onChange = (name, value) => {
  //   setValues(v => ({ ...v, [name]: value }));
  // };

  const onChange = (name, value) => {
  setValues(prev => {
    let updatedValue = value;

    if (Array.isArray(value)) {

      // ✅ NONE logic
      if (
        name === "substance_use"
     
      ) {
        if (value.includes("no_usage")) {
          updatedValue = ["no_usage"];
        } else {
          updatedValue = value.filter(v => v !== "none");
        }
      }

      // ✅ N/A logic
      if (name === "cognition_orientation") {
        if (value.includes("na")) {
          updatedValue = ["na"];
        } else {
          updatedValue = value.filter(v => v !== "na");
        }
      }

      // ✅ Risk Assessment logic
      if (name === "risk_assessment") {
        if (value.includes("no_current_risk")) {
          updatedValue = ["no_current_risk"];
        } else {
          updatedValue = value.filter(v => v !== "no_current_risk");
        }
      }

      // ✅ Drug Review logic (THIS PAGE IMPORTANT)
      if (name === "substance_use") {
        if (value.includes("no_usage")) {
          updatedValue = ["no_usage"];
        } else {
          updatedValue = value.filter(v => v !== "no_usage");
        }
      }
    }

    return {
      ...prev,
      [name]: updatedValue
    };
  });
};

  const handleAction = (type) => {
    if (type === "back") onBack?.();

    if (type === "clear") {
      setValues({});
      setSubmitted(false);
      localStorage.removeItem(storageKey);
    }

    if (type === "save") {
      localStorage.setItem(
        storageKey,
        JSON.stringify({ values, updatedAt: new Date() })
      );
      alert("Psychology draft saved");
    }
  };

  const handleSubmit = () => {
    const status = values.chief_complaint_status
    const text = values.chief_complaint
    if (!text && (status === "modified" || status === "new_complaint") ) {
      alert("Chief Complaint is required")
      return
    }
    setSubmitted(true);
    onSubmit?.(values);
    alert("Psychology assessment submitted");
  };

 

  /* ---------------- SIMPLE SCHEMA (OTHER TABS) ---------------- */
  const EMPTY_SCHEMA = {
    actions: [
      { type: "back", label: "Back" },
      { type: "clear", label: "Clear" },
      { type: "save", label: "Save" }
    ],
    sections: [{ fields: [] }]
  };

const SESSION_SCHEMA = {
    sections: [
      {
        fields: [


          {
            name: "session_type",
            label: "Session Type",
            type: "radio",
            options: [
              { label: "Individual", value: "individual" },
              { label: "Family", value: "family" },
              { label: "Couple", value: "couple" }
            ]
          },

          // {
          //   name: "attendance_status",
          //   label: "Attendance Status",
          //   type: "radio",
          //   options: [
          //     { label: "Present", value: "present" },
          //     { label: "No Show", value: "no_show" },
          //     { label: "Cancelled", value: "cancelled" }
          //   ]
          // },

        {
  name: "attender_present",
  label: "Accompanied By",
  type: "radio",
  options: [
    { label: "Yes", value: "yes" },
    { label: "No", value: "no" }
  ]
},
{
  name: "attender_name", // ✅ unique
  label: "Specific Name",
  type: "input",
  showIf: {
    field: "attender_present",
    equals: "yes"
  }
},
{
  name: "attender_relationship", // ✅ unique
  label: "Relationship",
  type: "input",
  showIf: {
    field: "attender_present",
    equals: "yes"
  }
},
        ]
      }
    ]
  };


  const SUBJECTIVE_SCHEMA = {
    actions: [
      { type: "back", label: "Back" },
      { type: "clear", label: "Clear" },
      { type: "save", label: "Save" }
    ],
    sections: [
      {
        fields: [
      
          {
  name: "chief_complaint_status",
  label: "Chief Complaint Status",
  type: "radio",
  options: [
    { label: "No Change", value: "no_change" },
    { label: "Modified", value: "modified" }
  ]
},

/* ✅ READ-ONLY FIELD (NO CHANGE) */
{
  name: "chief_complaint_readonly",
  label: "Chief Complaint",
  type: "input",
  placeholder: "No previous complaint available",
  disabled: true,
  showIf: {
    field: "chief_complaint_status",
    equals: "no_change"
  }
},

        


          {
            name: "chief_complaint",
            label: "Chief Complaint",
            required: true,
            type: "input",
            showIf: {
              field: "chief_complaint_status",
              oneOf: ["modified", "new_complaint"]
            }
          },
          {
            name: "hpi",
            label: "History of Presenting Illness (HPI)",
            type: "input"
          },
          
{
  name: "progress_since_last_session",
  label: "Progress since last session",
  type: "input",
  placeholder: "Enter progress details..."
},
          
          

// MAIN RADIO
{
  name: "new_symptoms",
  label: "New Symptoms / Issues",
  type: "radio",
  options: [
    { label: "None", value: "none" },
    { label: "Present", value: "present" }
  ]
},

// CATEGORY
{
  name: "symptoms_category",
  label: "Symptoms Category",
  type: "checkbox-group",
  options: [
    { label: "Mood", value: "mood" },
    { label: "Sleep", value: "sleep" },
    { label: "Appetite", value: "appetite" },
    { label: "Anxiety", value: "anxiety" },
    { label: "Psychosis", value: "psychosis" },
    { label: "Pain", value: "pain" },
    { label: "Others", value: "others" }
  ],
  showIf: {
    field: "new_symptoms",
    equals: "present"
  }
},

// ---------- MOOD ----------
{
  name: "mood_description",
  label: "Mood - Description",
  type: "input",
  showIf: {
    field: "symptoms_category",
    includes: "mood"
  }
},
{
  name: "mood_onset",
  label: "Mood - Onset",
  type: "date",
  showIf: {
    field: "symptoms_category",
    includes: "mood"
  }
},
{
  name: "mood_severity",
  label: "Mood - Severity",
  type: "radio",
  options: [
    { label: "Mild", value: "mild" },
    { label: "Moderate", value: "moderate" },
    { label: "Severe", value: "severe" }
  ],
  showIf: {
    field: "symptoms_category",
    includes: "mood"
  }
},

// ---------- SLEEP ----------
{
  name: "sleep_description",
  label: "Sleep - Description",
  type: "input",
  showIf: {
    field: "symptoms_category",
    includes: "sleep"
  }
},
{
  name: "sleep_onset",
  label: "Sleep - Onset",
  type: "date",
  showIf: {
    field: "symptoms_category",
    includes: "sleep"
  }
},
{
  name: "sleep_severity",
  label: "Sleep - Severity",
  type: "radio",
  options: [
    { label: "Mild", value: "mild" },
    { label: "Moderate", value: "moderate" },
    { label: "Severe", value: "severe" }
  ],
  showIf: {
    field: "symptoms_category",
    includes: "sleep"
  }
},

// ---------- OTHERS ----------
{
  name: "other_symptom_name",
  label: "Other Symptom",
  type: "input",
  placeholder: "Enter symptom name",
  showIf: {
    field: "symptoms_category",
    includes: "others"
  }
},
{
  name: "others_description",
  label: "Others - Description",
  type: "input",
  showIf: {
    field: "symptoms_category",
    includes: "others"
  }
},
{
  name: "others_onset",
  label: "Others - Onset",
  type: "date",
  showIf: {
    field: "symptoms_category",
    includes: "others"
  }
},
{
  name: "others_severity",
  label: "Others - Severity",
  type: "radio",
  options: [
    { label: "Mild", value: "mild" },
    { label: "Moderate", value: "moderate" },
    { label: "Severe", value: "severe" }
  ],
  showIf: {
    field: "symptoms_category",
    includes: "others"
  }
},
          {
            name: "description",
            label: "Description",
            type: "input",
            showIf: {
              field: "symptoms_category",
              equals: "others"
            }
          },
          {
            name: "onset",
            label: "Onset",
            type: "date",
            showIf: {
              field: "new_symptoms",
              equals: "present"
            }
          },
          {
            name: "severity",
            label: "Severity",
            type: "radio",
            options: [
              {label: "Mild", value: "mild"},
              {label: "Moderate", value: "moderate"},
              {label: "Severe", value: "severe"}
            ],
            showIf: {
              field: "new_symptoms",
              equals: "present"
            }
          },
          


// MAIN RADIO
{
  name: "medication_adherence",
  label: "Medication Adherence",
  type: "checkbox-group",
  options: [
    { label: "Fully Adherent", value: "fully_adherent" },
    { label: "Partially Adherent", value: "partially_adherent" },
    { label: "Non-Adherent", value: "non_adherent" },
    { label: "Not Applicable", value: "not_applicable" }
  ]
},

// FULLY ADHERENT INPUT
{
  name: "fully_adherent_input",
  label: "Details",
  type: "input",
  showIf: {
    field: "medication_adherence",
    equals: "fully_adherent"
  }
},

// PARTIALLY ADHERENT RADIO
{
  name: "partial_reason",
  label: "Partially Adherent Type",
  type: "radio",
  options: [
    { label: "Irregular", value: "irregular" },
    { label: "Missed Doses", value: "missed_doses" }
  ],
  showIf: {
    field: "medication_adherence",
    equals: "partially_adherent"
  }
},


{
  name: "non_adherent_reason",
  label: "Reason",
  
  type: "checkbox-group",
  options: [
    { label: "Forgot", value: "forgot" },
    { label: "Side effects", value: "side_effects" },
    { label: "Cost issues", value: "cost_issues" },
    { label: "Lack of insight", value: "lack_of_insight" },
    { label: "Intentional discontinuation", value: "intentional_discontinuation" },
    { label: "Access issues", value: "access_issues" },
    { label: "Other", value: "other" }
  ],
  showIf: {
    field: "medication_adherence",
    equals: "non_adherent"
  }
},

// OTHER INPUT (THIS IS WHAT YOU NEEDED)
{
  name: "non_adherent_other",
  label: "Please specify",
  type: "input",
  placeholder: "Enter reason...",
  showIf: {
    field: "non_adherent_reason",
    equals: "other"
  }
},


          {
            name: "description",
            label: "Description",
            type: "input",
            showIf: {
              field: "reason",
              equals: "other"
            }
          },
          
          /* ---------------- SUBSTANCE USE UPDATE ---------------- */

{
  name: "substance_use",
  // label: "Substance Use Update",
    label: "Drug Review",

  type: "checkbox-group",
  options: [
    { label: "No Usage", value: "no_usage" },
    { label: "No Change", value: "no_change" },
    { label: "Increased", value: "increased" },
    { label: "Reduced", value: "reduced" },
    { label: "Relapsed", value: "relapsed" },
    { label: "Abstinent", value: "abstinent" }
  ]
},

/* ✅ SHOW DETAILS ONLY WHEN RELEVANT */
{
  name: "substance_type",
  label: "Substance Type",
  type: "checkbox-group",
  options: [
    { label: "Alcohol", value: "alcohol" },
    { label: "Tobacco", value: "tobacco" },
    { label: "Cannabis", value: "cannabis" },
    { label: "Opioids", value: "opioids" },
    { label: "Others", value: "others" }
  ],
  showIf: {
    field: "substance_use",
    oneOf: ["increased", "relapsed"]
  }
},

/* ---------------- ALCOHOL ---------------- */
{
  name: "alcohol_frequency",
  label: "Alcohol - Frequency",
  type: "radio",
  options: [
    { label: "Daily", value: "daily" },
    { label: "Weekly", value: "weekly" },
    { label: "Occasional", value: "occasional" }
  ],
  showIf: {
    field: "substance_type",
    includes: "alcohol"
  }
},
{
  name: "alcohol_quantity",
  label: "Alcohol - Quantity",
  type: "input",
  placeholder: "e.g. 2 drinks/day",
  showIf: {
    field: "substance_type",
    includes: "alcohol"
  }
},
{
  name: "alcohol_last_use",
  label: "Alcohol - Last Use",
  type: "date",
  showIf: {
    field: "substance_type",
    includes: "alcohol"
  }
},

/* ---------------- TOBACCO ---------------- */
{
  name: "tobacco_frequency",
  label: "Tobacco - Frequency",
  type: "radio",
  options: [
    { label: "Daily", value: "daily" },
    { label: "Weekly", value: "weekly" },
    { label: "Occasional", value: "occasional" }
  ],
  showIf: {
    field: "substance_type",
    includes: "tobacco"
  }
},
{
  name: "tobacco_quantity",
  label: "Tobacco - Quantity",
  type: "input",
  placeholder: "e.g. 5 cigarettes/day",
  showIf: {
    field: "substance_type",
    includes: "tobacco"
  }
},
{
  name: "tobacco_last_use",
  label: "Tobacco - Last Use",
  type: "date",
  showIf: {
    field: "substance_type",
    includes: "tobacco"
  }
},

/* ---------------- CANNABIS ---------------- */
{
  name: "cannabis_frequency",
  label: "Cannabis - Frequency",
  type: "radio",
  options: [
    { label: "Daily", value: "daily" },
    { label: "Weekly", value: "weekly" },
    { label: "Occasional", value: "occasional" }
  ],
  showIf: {
    field: "substance_type",
    includes: "cannabis"
  }
},
{
  name: "cannabis_quantity",
  label: "Cannabis - Quantity",
  type: "input",
  placeholder: "e.g. 5 cigarettes/day",
  showIf: {
    field: "substance_type",
    includes: "cannabis"
  }
},
{
  name: "cannabis_last_use",
  label: "Cannabis - Last Use",
  type: "date",
  showIf: {
    field: "substance_type",
    includes: "cannabis"
  }
},

/* ---------------- OPIOIDS ---------------- */
{
  name: "opioids_frequency",
  label: "Opioids - Frequency",
  type: "radio",
  options: [
    { label: "Daily", value: "daily" },
    { label: "Weekly", value: "weekly" },
    { label: "Occasional", value: "occasional" }
  ],
  showIf: {
    field: "substance_type",
    includes: "opioids"
  }
},
{
  name: "opioids_quantity",
  label: "Opioids - Quantity",
  type: "input",
  placeholder: "e.g. 5 cigarettes/day",
  showIf: {
    field: "substance_type",
    includes: "opioids"
  }
},

{
  name: "opioids_last_use",
  label: "Opioids - Last Use",
  type: "date",
  showIf: {
    field: "substance_type",
    includes: "opioids"
  }
},

/* ---------------- OTHERS ---------------- */

{
  name: "others_frequency",
  label: "Others - Frequency",
  type: "radio",
  layout: "vertical",
  options: [
    { label: "Daily", value: "daily" },
    { label: "Weekly", value: "weekly" },
    { label: "Occasional", value: "occasional" },
    { label: "Other", value: "other" }
  ],
  showIf: {
    field: "substance_type",
    includes: "others" // 👈 changed
  }
},
{
  name: "others_frequency_other",
  label: "Please specify",
  type: "input",
  placeholder: "Enter frequency",
  showIf: {
    field: "others_frequency",
    equals: "other"
  }
},
{
  name: "others_quantity",
  label: "Others - Quantity",
  type: "input",
  placeholder: "e.g. amount/day",
  showIf: {
    field: "substance_type",
    includes: "others"
  }
},
{
  name: "others_last_use",
  label: "Others - Last Use",
  type: "date",
  showIf: {
    field: "substance_type",
    includes: "others"
  }
}
        ]
      }
    ]
  };

  const PSYCHOLOGY_CONTAINER_SCHEMA = {
    title: "Patient Information",
    sections: []
  };

  const OBJECTIVE_SCHEMA = {
    actions: SUBJECTIVE_SCHEMA.actions,
    sections: [
      {
        fields: [
          { type: "subheading", label: "Client’s Condition " },
         
          
              {
  name: "mood_affect",
  label: "Mood & Affect",
  type: "radio",
  options: [
    { label: "No Change", value: "no_change" },
    { label: "Notable Change ", value: "Notable_Change " }
    
  ]
},
{
  name: "mood_affect_details",
  label: "Specify Details",
  type: "input",
  placeholder: "Enter details",
  showIf: {
    field: "mood_affect",
    equals: "Notable_Change " // 👈 trigger here
  }
},

         
         {
  name: "thought_process",
  label: "Thought Process",
  type: "radio", // or keep single-select if you want
  options: [
    { label: "No Change", value: "no_change" },
    { label: "Notable Change ", value: "Notable_Change " },
    
  ]
},
{
  name: "thought_process_details",
  label: "Specify Details",
  type: "input",
  showIf: {
    field: "thought_process",
    equals: "Notable_Change "
  }
},
{
  name: "behavior_functioning",
  label: "Behavior / Functioning",
  type: "radio",
  options: [
    { label: "No Change", value: "no_change" },
    { label: "Notable Change", value: "Notable_Change" },
    
  ]
},
{
  name: "behavior_functioning_details",
  label: " Specify Details",
  type: "input",
  showIf: {
    field: "behavior_functioning",
    equals: "Notable_Change",
  }
},{
  name: "medical_condition",
  label: "Medical Condition",
  type: "radio",
  options: [
    { label: "No Change", value: "no_change" },
    { label: "Notable Change ", value: "Notable_Change " }
  ]
},
{
  name: "medical_condition_details",
  label: " Specify Details",
  type: "input",
  showIf: {
    field: "medical_condition",
    equals: "Notable_Change "
  }
},
{
  name: "substance_use",
  label: "Substance Use",
  type: "radio",
  options: [
    { label: "No Change", value: "no_change" },
    { label: "Notable Change ", value: "Notable_Change " },
    
  ]
},
{
  name: "substance_use_details",
  label: " Specify Details",
  type: "input",
  showIf: {
    field: "substance_use",
    equals: "Notable_Change "
  }
},
          {type:"subheading", label: "Risk Assessment"},
         {
            name: "risk_assessment",
            label: "Risk Status",
            type: "radio",
            options: [
              { label: "No risk", value: "no_risk" },
              { label: "Suicidal Ideation", value: "Suicidal Ideation" },
              { label: "Homicidal ideation", value: "homicidal_ideation" },
              { label: "Self-harm risk", value: "self_harm_risk" },
              { label: "Risk to others", value: "risk_to_others" }
            ]
          },
          {
            name: "risk_checkbox",
            label: "",
            type: "checkbox-group",
            options:[
              {label: "Ideation", value: "ideation"},
              {label: "Plan", value: "plan"},
              {label: "Intent", value: "Intent"},
              {label: "Attempt", value: "attempt"}
            ],
            showIf: {
              field: "risk_assessment",
              oneOf: ["Suicidal Ideation","self_harm_risk", "risk_to_others"]
            }
          }
          
         
        ]
      }
    ]
  };
// const OBJECTIVE_SCHEMA = {
//     actions: SUBJECTIVE_SCHEMA.actions,
//     sections: [
//       {
//         fields: [
//           {
//             type: "subheading",
//             label: "Psychology Assessments"
//           },
//           {
//             name: "psychology_assessments",
//             type: "assessment-launcher",
//             options: [
//               { label: "Depression Anxiety Stress Scale (DASS-21)", value: "dass21" },
//               { label: "Perceived Stress Scale (PSS)", value: "pss" },
//               { label: "Patient Health Questionnaire (PHQ-9)", value: "phq9" },
//               { label: "Generalized Anxiety Disorder (GAD-7)", value: "gad7" },
//               { label: "Hamilton Depression Rating Scale (HAM-D)", value: "hamd" },
//               { label: "Hamilton Anxiety Rating Scale (HAM-A)", value: "hama" }
//             ]
//           },
//           {
//             type: "subheading",
//             label: "Appearance & Behaviour"
//           },
//           {
//             type: "subheading",
//             label: "Appearance"
//           },
//           {
//             name: "appearance_grooming",
//             label: "Grooming",
//             type: "radio",
//             options: [
//               { label: "Well-groomed", value: "well_groomed" },
//               { label: "Adequate", value: "adequate" },
//               { label: "Poor", value: "poor" },
//               { label: "Not Applicable", value: "na" }
//             ]
//           },
//           {
//             name: "appearance_dress",
//             label: "Dress",
//             type: "radio",
//             options: [
//               { label: "Appropriate", value: "appropriate" },
//               { label: "Inappropriate", value: "inappropriate" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "appearance_hygiene",
//             label: "Hygiene",
//             type: "radio",
//             options: [
//               { label: "Clean", value: "clean" },
//               { label: "Poor", value: "poor" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "appearance_build_posture",
//             label: "Build/Posture",
//             type: "radio",
//             options: [
//               { label: "Thin", value: "thin" },
//               { label: "Average", value: "average" },
//               { label: "Overweight", value: "overweight" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "appearance_visible_marks",
//             label: "Visible Marks",
//             type: "checkbox-group",
//             inlineWithLabel: true,
//             options: [
//               { label: "Scars", value: "scars" },
//               { label: "Bruises", value: "bruises" },
//               { label: "Tattoos", value: "tattoos" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             type: "subheading",
//             label: "Behaviour"
//           },
//           {
//             name: "behavior_cooperation",
//             label: "Cooperation",
//             type: "radio",
//             options: [
//               { label: "Cooperative", value: "cooperative" },
//               { label: "Guarded", value: "guarded" },
//               { label: "Uncooperative", value: "uncooperative" },
//               { label: "Hostile", value: "hostile" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "behavior_eye_contact",
//             label: "Eye contact",
//             type: "radio",
//             options: [
//               { label: "Good", value: "good" },
//               { label: "Poor", value: "poor" },
//               { label: "Avoidant", value: "avoidant" },
//               { label: "Intense", value: "intense" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "behavior_psychomotor_activity",
//             label: "Psychomotor activity",
//             type: "radio",
//             options: [
//               { label: "Normal", value: "normal" },
//               { label: "Agitated", value: "agitated" },
//               { label: "Retarded", value: "retarded" },
//               { label: "Restless", value: "restless" }
//             ]
//           },
//           {
//             name: "behavior_impulse_control",
//             label: "Impulse control",
//             type: "radio",
//             options: [
//               { label: "Intact", value: "intact" },
//               { label: "Impaired", value: "impaired" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "behavior_attention",
//             label: "Attention",
//             type: "radio",
//             options: [
//               { label: "Alert", value: "alert" },
//               { label: "Distracted", value: "distracted" },
//               { label: "Focused", value: "focused" }
//             ]
//           },
//           {
//             name: "behavior_engagement_attitude",
//             label: "Engagement/Attitude",
//             type: "radio",
//             options: [
//               { label: "Open", value: "open" },
//               { label: "Defensive", value: "defensive" },
//               { label: "Withdrawn", value: "withdrawn" },
//               { label: "Evasive", value: "evasive" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "behavior_affect_behavioral_state",
//             label: "Affect/behavioral state",
//             type: "radio",
//             options: [
//               { label: "Calm", value: "calm" },
//               { label: "Anxious", value: "anxious" },
//               { label: "Tearful", value: "tearful" },
//               { label: "Agitated", value: "agitated" },
//               { label: "Tense", value: "tense" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "behavior_activity_level",
//             label: "Activity level",
//             type: "radio",
//             options: [
//               { label: "Relaxed", value: "relaxed" },
//               { label: "Restless", value: "restless" },
//               { label: "Fidgety", value: "fidgety" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             type: "subheading",
//             label: "Speech"
//           },
//           {
//             name: "speech_rate",
//             label: "Rate",
//             type: "radio",
//             options: [
//               { label: "Normal", value: "normal" },
//               { label: "Rapid/Pressured", value: "rapid_pressured" },
//               { label: "Slow", value: "slow" },
//               { label: "Disorganized", value: "disorganized" },
//               { label: "Poverty", value: "poverty" },
//               { label: "Variable", value: "variable" },
//               { label: "Mute", value: "mute" },
//               { label: "Echolalia", value: "echolalia" }
//             ]
//           },
//           {
//             name: "speech_volume",
//             label: "Volume",
//             type: "radio",
//             options: [
//               { label: "Normal", value: "normal" },
//               { label: "Loud", value: "loud" },
//               { label: "Soft", value: "soft" },
//               { label: "Whispered", value: "whispered" }
//             ]
//           },
//           {
//             name: "speech_fluency",
//             label: "Fluency",
//             type: "radio",
//             options: [
//               { label: "Fluent/Coherent", value: "fluent_coherent" },
//               { label: "Hesitant", value: "hesitant" },
//               { label: "Slurred", value: "slurred" },
//               { label: "Dysarthric", value: "dysarthric" },
//               { label: "Stammering", value: "stammering" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "speech_quantity",
//             label: "Quantity",
//             type: "radio",
//             options: [
//               { label: "Normal", value: "normal" },
//               { label: "Talkative", value: "talkative" },
//               { label: "Poverty of speech", value: "poverty_of_speech" },
//               { label: "Spontaneous expansive", value: "spontaneous_expansive" }
//             ]
//           },
//           {
//             name: "speech_tone_prosody",
//             label: "Tone/Prosody",
//             type: "radio",
//             options: [
//               { label: "Normal", value: "normal" },
//               { label: "Dull", value: "dull" },
//               { label: "Monotonous/Flat", value: "monotonous_flat" },
//               { label: "Flat", value: "flat" },
//               { label: "Loud", value: "loud" },
//               { label: "Whispered", value: "whispered" }
//             ]
//           },
//           {
//             type: "subheading",
//             label: "Mood & Affect"
//           },
//           {
//             name: "mood_observed",
//             label: "Mood",
//             type: "input"
//           },
//           {
//             name: "affect_observed",
//             label: "Affect",
//             type: "checkbox-group",
//             inlineWithLabel: true,
//             options: [
//               { label: "Euthymic", value: "euthymic" },
//               { label: "Constricted", value: "constricted" },
//               { label: "Flat", value: "flat" },
//               { label: "Blunted", value: "blunted" },
//               { label: "Labile", value: "labile" },
//               { label: "Congruent", value: "congruent" },
//               { label: "Incongruent", value: "incongruent" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             type: "subheading",
//             label: "Thought"
//           },
//           {
//             name: "thought_form_process",
//             label: "Form/Process",
//             type: "checkbox-group",
//             options: [
//               { label: "Normal", value: "normal" },
//               { label: "Loose associations", value: "loose_associations" },
//               { label: "Clang associations", value: "clang_associations" },
//               { label: "Tangential", value: "tangential" },
//               { label: "Circumstantial", value: "circumstantial" },
//               { label: "Flight of ideas", value: "flight_of_ideas" },
//               { label: "Word salad", value: "word_salad" },
//               { label: "Poverty of thought", value: "poverty_of_thought" },
//               { label: "Pressure of thought", value: "pressure_of_thought" },
//               { label: "Thought blocking", value: "thought_blocking" },
//               { label: "Spontaneous", value: "spontaneous" }
//             ]
//           },
//           {
//             name: "thought_content_observed",
//             label: "Content (observed/reported)",
//             type: "checkbox-group",
//             options: [
//               { label: "Delusions (Grandiose, Erotomanic, Somatic, Referential, Persecutory, Control, Religious)", value: "delusions" },
//               { label: "Hallucinations", value: "hallucinations" },
//               { label: "Illusions", value: "illusions" },
//               { label: "Suicidal/Homicidal ideation", value: "suicidal_homicidal_ideation" },
//               { label: "Paranoia", value: "paranoia" },
//               { label: "Obsessions", value: "obsessions" },
//               { label: "Compulsions", value: "compulsions" },
//               { label: "Thought insertion", value: "thought_insertion" },
//               { label: "Thought broadcasting", value: "thought_broadcasting" },
//               { label: "Thought withdrawal", value: "thought_withdrawal" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             type: "subheading",
//             label: "Cognition"
//           },
//           {
//             name: "cognition_orientation",
//             label: "Orientation",
//             type: "checkbox-group",
//             inlineWithLabel: true,
//             options: [
//               { label: "Person", value: "person" },
//               { label: "Place", value: "place" },
//               { label: "Time", value: "time" },
//               { label: "Situation", value: "situation" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "cognition_attention_concentration",
//             label: "Attention/Concentration",
//             type: "radio",
//             options: [
//               { label: "Intact", value: "intact" },
//               { label: "Mildly impaired", value: "mildly_impaired" },
//               { label: "Severely impaired", value: "severely_impaired" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "cognition_memory_immediate",
//             label: "Memory",
//             type: "radio",
//             options: [
//               { label: "Immediate", value: "immediate" },
//               { label: "Intact", value: "intact" },
//               { label: "Impaired", value: "impaired" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "cognition_memory_recent",
//             label: "Recent",
//             type: "radio-matrix",
//             matrixHeaderLabel: "Category",
//             options: [
//               { label: "Intact", value: "intact" },
//               { label: "Impaired", value: "impaired" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "cognition_memory_remote",
//             label: "Remote",
//             type: "radio-matrix",
//             options: [
//               { label: "Intact", value: "intact" },
//               { label: "Impaired", value: "impaired" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//             name: "cognition_abstract_thinking",
//             label: "Abstract thinking",
//             type: "radio-matrix",
//             options: [
//               { label: "Intact", value: "intact" },
//               { label: "Impaired", value: "impaired" },
//               { label: "N/A", value: "na" }
//             ]
//           },
//           {
//   type: "subheading",
//   label: "Additional Comments"
// },
// {
//   name: "additional_comments",
//   label: "Add additional comments (Other/Specify)",
//   type: "input",
//   placeholder: "Enter any overall observations, notes, or summary..."
// },
//         ]
//       }
//     ]
//   };
  const ASSESSMENT_SCHEMA = {
    actions: SUBJECTIVE_SCHEMA.actions,
    sections: [
      {
        fields: [
            // { type: "subheading", label: "Clinical Impression"},
          {
            name: "clinicalImpression",
            label: "Clinical Impression",
            type: "input"
          },
          // { type: "subheading", label: "Clinical Summary"},
          {
            name: "clinical_progress_summary",
            label: "Clinical Progress Summary",
            type: "input"
          },
          // { type: "subheading", label: "Diagnosis"},
          // {
          //   name: "severity",
          //   label: "Severity",
          //   type: "radio",
          //   options: [
          //     { label: "Mild", value: "mild" },
          //     { label: "Moderate", value: "moderate" },
          //     { label: "Severe", value: "severe" }
          //   ]
          // },
          
        ]
      }
    ]
  };

  /* ---------------- PLAN SCHEMA WITH GOALS ---------------- */
  const PLAN_SCHEMA = {
    actions: EMPTY_SCHEMA.actions,
    sections: [
      {
        fields: [
           { type: "subheading", label: "Short-Term Goals (2–4 weeks)" },
        {
            type: "dynamic-goals",
            name: "short_term_goals"
          },
          { type: "subheading", label: "Long-Term Goals (6–12 weeks)" },
          {
            type: "dynamic-goals",
            name: "long_term_goals"
          },
          
          { type: "subheading", label: "Therapeutic Interventions" },

          {
            name: "continue_same_plan",
            label: "Continue Same Plan",
            type: "radio",
            options: [
              { label: "Yes", value: "yes" },
              { label: "No", value: "no" }
            ]
          },
          {
            name: "plan_changes",
            label: "Specify changes",
            type: "input",
            showIf: {
              field: "continue_same_plan",
              equals: "no"
            }
          },

          {
            name: "interventions_delivered",
            label: "Therapeutic Interventions Delivered in Session",
            type: "input"
          },

          {
            name: "client_response",
            label: "Client’s Response / Progress Toward Goals",
            type: "input"
          },

          {
            name: "plan_additional_info",
            label: "Plan / Additional Information (Between sessions)",
            type: "input"
          },

          { type: "subheading", label: "Risk Management Plan" },

          {
            name: "safety_plan_initiated",
            label: "Safety Plan Initiated",
            type: "radio",
            options: [
              { label: "Yes", value: "yes" },
              { label: "No", value: "no" }
            ]
          },

          {
            name: "family_involvement",
            label: "Family Involvement",
            type: "radio",
            options: [
              { label: "Yes", value: "yes" },
              { label: "No", value: "no" }
            ]
          },

          {
            name: "psychiatric_referral",
            label: "Psychiatric Referral",
            type: "radio",
            options: [
              { label: "Yes", value: "yes" },
              { label: "No", value: "no" }
            ]
          },

          {
            name: "psychiatric_referral_specify",
            label: "Specify",
            type: "input",
            showIf: {
              field: "psychiatric_referral",
              equals: "yes"
            }
          },

          { type: "subheading", label: "Follow-up" },

          {
            name: "follow_up_visit_scheduled",
            label: "Follow-up Visit Scheduled",
            type: "date"
          },

          // {
          //   name: "follow_up_specify",
          //   label: "Specify",
          //   type: "input"
          // }
        ]
      }
    ]
  };
const tabOrder = ["subjective", "objective", "assessment", "plan"];
const activeTabIdx = tabOrder.indexOf(activeTab);

 const schemaMap = {
  subjective: SUBJECTIVE_SCHEMA,
  objective: OBJECTIVE_SCHEMA,
  assessment: ASSESSMENT_SCHEMA,
  plan: PLAN_SCHEMA
};

return (
  <PatientContext.Provider value={patient}>
    <div style={mainContent}>

      {/* PATIENT INFO */}
      <CommonFormBuilder
                schema={{ title: "Patient Information", sections: [] }}
                values={{}}
                onChange={() => {}}
              >
                <PatientInformationBlock
                  patient={patient}
                  patientHistory={patientHistory}
                  setPatientHistory={setPatientHistory}
                />
              
                <button style={doctorsReportBtn}>
                  Doctors Reports
                </button>
              </CommonFormBuilder>
      {/* <CommonFormBuilder
        schema={{ sections: [] }}
        values={{}}
        onChange={() => {}}
      >
        <PatientCard patient={patient} />
      </CommonFormBuilder> */}
{/* ✅ SESSION DETAILS ABOVE TABS */}
        <CommonFormBuilder
          schema={SESSION_SCHEMA}
          values={values}
          onChange={onChange}
        />



      {/* TABS */}
         <div style={tabBar}>
          {["subjective", "objective", "assessment", "plan"].map(tab => (
            <div
              key={tab}
              style={activeTab === tab ? tabActive : tabBtn}
              onClick={() => setActiveTab(tab)}
            >
              {tab.toUpperCase()}
            </div>
          ))}
        </div>

      {/* FORM */}
      <CommonFormBuilder
        schema={schemaMap[activeTab]}
        values={values}
        onChange={onChange}
        submitted={submitted}
        onAction={handleAction}
      >

       

        {/* SUBMIT */}
        
        <div style={submitRow}>
          {activeTab !== "plan" ? (
            <button style={submitBtn} onClick={() => setActiveTab(tabOrder[activeTabIdx + 1])}>
              Next
            </button>
          ) : (
            <button style={submitBtn} onClick={handleSubmit}>
               Submit Psychology Assessment
            </button>
          )}
        </div>

      </CommonFormBuilder>

    </div>
  </PatientContext.Provider>
);
};
/* ---------------- STYLES ---------------- */

const mainContent = { width: "100%" };

const tabBar = {
  display: "flex",
  gap: 12,
  justifyContent: "center",
  borderBottom: "1px solid #ddd",
  marginBottom: 12
};

const tabBtn = {
  padding: "10px 22px",
  fontWeight: 600,
  cursor: "pointer",
  color: "#0f172a"
};

const tabActive = {
  ...tabBtn,
  borderBottom: "3px solid #2451b3",
  color: "#2451b3"
};

const submitRow = {
  display: "flex",
  justifyContent: "flex-end",
  marginTop: 20
};

const submitBtn = {
  padding: "12px 32px",
  background: "#2563EB",
  color: "#fff",
  border: "none",
  borderRadius: 10,
  fontSize: 15,
  fontWeight: 700
};


const section = { marginBottom: 24 };

const patientGrid = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  gap: 12
};
const input = {
          width: "100%",
          minHeight: 90,
          marginTop: 6,
          marginBottom: 12,
          padding: "10px 12px",
          borderRadius: 6,
          border: "1px solid #d1d5db",
          fontSize: 14,
          resize: "vertical"
};
const alertBtn = {
  marginTop: 10,
          padding: "10px 20px",
          borderRadius: 6,
          border: "1.5px solid #007bff",
          background: "#007bff",
          color: "#fff",
          fontWeight: 600,
          cursor: "pointer"
};

const doctorsReportBtn = {
  padding: "10px 20px", background: "#2563EB", color: "#fff",
  border: "none", borderRadius: 6, fontSize: 14,
  fontWeight: 600, cursor: "pointer", marginTop: 8
};